apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-demo-service
  namespace: demo
  labels:
    release: stable
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/instance: demo-service
spec:
  selector:
    matchLabels:
      release: stable
      app.kubernetes.io/name: demo-service
  replicas: 1
  template:
    metadata:
      labels:
        release: stable
        app.kubernetes.io/name: demo-service
    spec:
      containers:
        - name: demo-service
          image: achin16/demo-service:latest
          env:
            - name: WORLD_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: demo-service-demo-service
                  key: world_service_address
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: demo-service-demo-service
                  key: message
          ports:
            - containerPort: 8080