kind: Service
apiVersion: v1
metadata:
  name: demo-service-demo-service
  namespace: default
  labels:
    release: stable
    instance: demo-service
spec:
  selector:
    release: stable
    app.kubernetes.io/name: demo-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: NodePort